# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_auto_20170506_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status_from_customer', models.BooleanField(default=False)),
                ('status_from_artisan', models.BooleanField(default=False)),
                ('transaction_status', models.BooleanField(default=False)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='user.UserAccount')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='user.UserAccount')),
            ],
            options={
                'verbose_name_plural': 'Transaction',
            },
        ),
    ]
