# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170426_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occcupation',
            new_name='Occupation',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usera_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
