# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170426_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='acc_type',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('regular', 'Regular')], default='regular', max_length=15),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
