# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_useraccount_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_path),
        ),
    ]
