# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170501_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='occcupation',
            field=models.CharField(blank=True, choices=[('barber', 'Barber'), ('electrian', 'Electrian'), ('mechanic', 'Mechanic'), ('caterer', 'Caterer'), ('hair_dresser', 'Hair_dresser'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('welder', 'Welder'), ('others', 'Others')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='skill',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
