# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20170505_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='occcupation',
            new_name='occupation',
        ),
    ]
