# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170506_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10)),
                ('friends', models.ManyToManyField(related_name='_test_friends_+', to='user.Test')),
            ],
        ),
    ]
