# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
