# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20170507_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='courtesy_rating',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall_rating',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price_rating',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='quality_rating',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
    ]
